### ISSUE TITLE
Please create the following namespaces for Maneki

### ISSUE THREAD

**Issue by Hsn723** [cybozu-go/neco-apps#1238]
## What

We'd like to request the creation of the following namespaces for use by the Maneki team in all environments: `app-maneki-static-cybozu-com` and `app-forest-certs`

## How

Describe how to address the issue.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by yokaze** [comment]
PR https://github.com/cybozu-go/neco-apps/pull/1241

**Comment by yokaze** [comment]
@Hsn723 The namespaces are created on stage and prod environments. Please check 🙇‍♂️

**Comment by Hsn723** [comment]
@yokaze Thanks, I've confirmed it
