### ISSUE TITLE
Please add a Teleport node for the Garoon team

### ISSUE THREAD

**Issue by Hsn723** [cybozu-go/neco-apps#1341]
## What

Similarly to the Maneki team, we'd like to request a Teleport node for the Garoon team for operations purpose.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by kfyharukz** [comment]
#1349

**Comment by kfyharukz** [comment]
Done.
