### ISSUE TITLE
Please create following namespaces for new apps

### ISSUE THREAD

**Issue by pddg** [cybozu-go/neco-apps#1403]
## What

We'd like to request the creation of the following namespaces for new apps in all environments: `app-endpoint-discovery` and `app-es-cluster-allocator`

## How

Describe how to address the issue.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by yokaze** [comment]
PR: #1406
