### ISSUE TITLE
Investigate and improve connections for Teleport Application Access

### ISSUE THREAD

**Issue by morimoto-cybozu** [cybozu-go/neco-apps#1954]
## What

Accessing Alertmanager applications via Teleport sometimes fails with a 50X error, especially after the weekly reboot of worker nodes.
This can be repaired by restarting problematic application Pods, but we want to prevent the problem if possible.

## How

The problem may be caused by the `auth_servers` configuration of applications.
Try listing proxy Pod names.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by umezawatakeshi** [comment]
fixed in https://github.com/cybozu-go/neco/issues/1848
