### ISSUE TITLE
[Question] Can you please explain how you manage secrets?

### ISSUE THREAD

**Issue by alwaysastudent** [cybozu-go/neco-apps#596]
I am looking at your repository as a reference for manifest management and GitOps in general. It has been very helpful to see how you guys do your configuration management.

One thing, I couldn't understand is the way you manage your sensitive secrets. Can you please give any pointers on a good way to do secrets management? Have you structured your private repo to manage the secrets in the same way as this repo? If so are you following the same structure of namespace specific directories with env overlays to store secrets as well?

**Comment by kfyharukz** [comment]
Hi, @alwaysastudent 

`neco-apps` has multiple target environments, that is, kind/gcp environments for test, and staging/production datacenter environments.

For the test environments, there are no sensitive secrets, so we manage them in the public repository (i.e. cybozu-go/neco-apps/secret).

For the staging/production environments, we manage the sensitive secrets in the private repository (i.e. cybozu-private/neco-apps-secret). 

The two repositories have `Secret` resources that have **the same name**.  In other words, the two repositories are in a mapping relationship.

Therefore, we can deploy the secrets only by switching the target repository in the application config of ArgoCD (located in `arogcd-config`) without any manifest modification.

**Comment by alwaysastudent** [comment]
@kfyharukz - Thank you so much for explaining this so well. I appreciate your reply, I understand well now. 

I have a couple more questions regarding the team-management and the tenant configs.   
Can you please give me an idea of how you do this?  What gets configured within "cybozu-private/maneki-apps" and what gets configured in this repo for that tenant? Does the tenant maintain only configurations that are scoped within their own namespaces? Will they onboard their namespace using this repo?
