### ISSUE TITLE
[Question] Query regarding the team-management

### ISSUE THREAD

**Issue by alwaysastudent** [cybozu-go/neco-apps#605]
I have a couple of questions, if you don't mind, regarding how you do the team/tenant management

1) Why do you need to have this intermediate app `tenant-app-of-apps` when you could have just created the app of apps  `maneki-apps` from a `default` project and got the same effect ?

2) What is allowed to configured within "cybozu-private/maneki-apps" and what gets configured in this repo for that tenant? Does each tenant maintain the configurations that are only in the scope of their own namespaces? I assume `cybozu-private/maneki-apps` use `maneki` project to configure their ArgoCD apps. If that is the case, how do they configure something like a PV/StorageClass for example? Can you please give me a small overview of how you do this in general?

Thank you.

**Comment by kfyharukz** [comment]
@alwaysastudent 
`tenant-app-of-apps` is the `Project` to enable ArgoCD app sync with repositories outside of `neco-apps`. The `AppProject` is restricted not to sync any other resources than Application.

The resources in `team-management/base/<group name>` contains permission settings (i.e. RBAC) for the specified group. ArgoCD SSO binds each group with its group RBAC.

For example, a member in maneki group is attached maneki group attribution by ArgoCD SSO, and the member gets admin role only for maneki namespace as written in `team-management/base/maneki/maneki.yaml` .

**Comment by alwaysastudent** [comment]
@kfyharukz - Thank you for the reply. I get the purpose of the `tenant-app-of-apps` project, now.

But I am still not sure about the 2nd question. I assume the ArgoCD apps within the `cybozu-private/maneki-apps` are configured as the `maneki`  "AppProject". If that is the case, they are not allowed to create/configure any cluster-wide resources that are not in their namespace. So, how can they configure something like a PV/StorageClass for example?

**Comment by kfyharukz** [comment]
@alwaysastudent 
You're right.

A maneki member cannot create cluster-wide resource such as PV/StorageClass, it means maneki group isn't an infrastructure admin group  (Note that a maneki member can create PV intermediately by PVC).

**Comment by alwaysastudent** [comment]
@kfyharukz - Thank you for the reply.

Is there any set process/guidelines for them, when they want to configure any cluster-wide resource, or say some blacklisted resources like Limits/ResourceQuotas, etc.?

Will they configure such resources under this repo? If so, where and how?

**Comment by kfyharukz** [comment]
@alwaysastudent 
So far we have no such use for it. 

Of course, you can add `(Cluster)Role` and `ClusterRoleBinding` which allows to CRUD for the desired resource. However, I think it is dangerous. Infra-admin should be responsible for cluster-wide resources.

FYI, a new architecture for Kubernetes multi-tenancy is under discussing and developing like kiosk/loft.
https://github.com/kiosk-sh/kiosk
https://github.com/loft-sh/loft
