### ISSUE TITLE
Please create a namespace for maneki

### ISSUE THREAD

**Issue by Hsn723** [cybozu-go/neco-apps#628]
## What

We'd like to request the creation of a namespace named `app-comconv-earthlab` for use by the Maneki team (all environments).

## How

Describe how to address the issue.

## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by ymmt2005** [comment]
@zoetrope @ysksuzuki Please handle this.  Thank you.

**Comment by morimoto-cybozu** [comment]
@Hsn723 
Created in #631.

**Comment by Hsn723** [comment]
@morimoto-cybozu Thank you, I was able to confirm it.
